CATEGORIES = [
    {
        "id": "belleza",
        "name": "Accesorios Belleza",
        "emoji": "💄",
        "color": "#d63384",
        "bg_color": "#fce4f0",
        "url": "https://www.amazon.com/gp/bestsellers/beauty/11062051/",
        "panama_base": 90,
        "panama_notes": "Alta demanda en belleza. Viral en TikTok/IG. Sin talla = sin devoluciones.",
    },
    {
        "id": "viaje",
        "name": "Accesorios Viaje",
        "emoji": "🧳",
        "color": "#1565c0",
        "bg_color": "#e3f2fd",
        "url": "https://www.amazon.com/gp/bestsellers/luggage/6740501/",
        "panama_base": 88,
        "panama_notes": "Panamá = hub de tránsito. Packing cubes, organizadores. Demanda constante.",
    },
    {
        "id": "hogar",
        "name": "Organizadores Hogar",
        "emoji": "🏠",
        "color": "#2e7d32",
        "bg_color": "#e8f5e9",
        "url": "https://www.amazon.com/gp/bestsellers/home-garden/7846770011/",
        "panama_base": 85,
        "panama_notes": "Apartamentos compactos en PtyCity. Antes/después viral en redes.",
    },
    {
        "id": "mascotas",
        "name": "Accesorios Mascotas",
        "emoji": "🐾",
        "color": "#e65100",
        "bg_color": "#fff3e0",
        "url": "https://www.amazon.com/gp/bestsellers/pet-supplies/",
        "panama_base": 83,
        "panama_notes": "Mercado emocional: los dueños no escatiman. Recompra alta.",
    },
    {
        "id": "fitness",
        "name": "Fitness Accesorios",
        "emoji": "🏋️",
        "color": "#6a1b9a",
        "bg_color": "#f3e5f5",
        "url": "https://www.amazon.com/gp/bestsellers/sporting-goods/3407731/",
        "panama_base": 82,
        "panama_notes": "Cultura de gym muy fuerte en Panamá. Videos de demostración convierten bien.",
    },
    {
        "id": "bebe",
        "name": "Accesorios Bebé",
        "emoji": "👶",
        "color": "#00838f",
        "bg_color": "#e0f7fa",
        "url": "https://www.amazon.com/gp/bestsellers/baby-products/166827011/",
        "panama_base": 75,
        "panama_notes": "Alta natalidad. Compra emocional: el precio no es barrera para los padres.",
    },
    {
        "id": "tech",
        "name": "Tech Lifestyle",
        "emoji": "📱",
        "color": "#37474f",
        "bg_color": "#eceff1",
        "url": "https://www.amazon.com/gp/bestsellers/wireless/2335752011/",
        "panama_base": 70,
        "panama_notes": "Alta penetración smartphones. Accesorios con identidad visual se diferencian.",
    },
]
